version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.3
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
      - "9440:9440"
    volumes:
      - ./docker/clickhouse_data:/var/lib/clickhouse
      - ./docker/clickhouse_log:/var/log/clickhouse-server
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
      CLICKHOUSE_DB: default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
